eth_name: "en0"
analyze_threads: 1
input_dir: "./input"
input_format: "r,12,3,4,1,2,5,6,7,14,19,15,13"
backup_dir: "./backup"
online_mode: true
domain_counter_enable: false
executed_hour: 10


task_infos:
  apt:
    enable: true
    filter_ip_ruler:
      - "ip.list"
      - "./v6.list"
    filter_domain_ruler:
    is_match_resolve_ip: true
    output_dir: "./data/apt"
    output_format: "jituan"
    is_upload: false
    is_gzip: true
    file_max_size: 200M
    file_max_time: 1h

  aliyun:
    enable: true
    filter_ip_ruler:
    filter_domain_ruler:
      -  "./aliyun.list"
    output_dir: "./data/aliyun"
    output_format: "jituan"
    domain_exact_match: false
    is_upload: false
    is_gzip: true
    file_max_size: 200M
    file_max_time: 1h

  wuxi-AI:
    enable: true
    filter_ip_ruler:
    filter_domain_ruler:
      -  "./wuxi-AI.list"
    output_dir: "./data/wuxi-AI"
    output_format: "jituan"
    is_upload: false
    is_gzip: true
    file_max_size: 200M
    file_max_time: 1h